#!/bin/bash

PROD_HOST="appuser@188.166.74.118"
PROD_PATH="/app"

PROD_ROOT=$PROD_HOST:$PROD_PATH

lessc less/less.main.less www/static/css/styles.css

lein cljsbuild once

scp www/index.html $PROD_ROOT/index.html
scp www/static/js/main.js $PROD_ROOT/static/js/
scp www/static/css/styles.css $PROD_ROOT/static/css/
